version: 1
formatters:
  sample:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console_handler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: sample
    stream: ext://sys.stdout
loggers:
  sampleLogger:
    level: DEBUG
    handlers: [console_handler]
    propagate: no
root:
  level: DEBUG
  handlers: [console_handler]
